# Generated by Django 3.1.4 on 2021-01-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail_content',
            field=models.TextField(default='add News'),
        ),
    ]
