# Generated by Django 3.1.5 on 2021-01-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='URL',
            field=models.TextField(default='#'),
        ),
    ]
