# Generated by Django 3.1.5 on 2021-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='URL',
            field=models.CharField(default='#', max_length=220),
        ),
    ]
